### ISSUE TITLE
A simple test with fgfs 2020.4.0

### ISSUE THREAD

**Issue by Attigliuzzo** [tdammers/DC3-neo#1]
I found your project and i tested under FGFS 2020.4.0 (Debian testing), there are some errors:

`
FlightGear 2020.4.0 error report, created at mer, 17 mag 2023 16:52:48 GMT
Category:error-category-aircraft-from-hangar
	Parameter:dc3-neo

Error 1
	code:error-aircraft-systems
	type:error-type-not-found
	when:16:51:21 GMT
	Autopilot XML not found:Aircraft/DC3-neo/PropertyRules/autopilot-sperry.xml
	location:Aircraft/DC3-neo/PropertyRules/autopilot-sperry.xml
	context:
	preceeding log:
		/build/workspace/Linux-nightly/flightgear/src/FDM/JSBSim/JSBSim.cxx:-242:	num engines = 2
		/build/workspace/Linux-nightly/flightgear/src/Instrumentation/instrument_mgr.cxx:-83:	Reading instruments from Path "/fgdata/Aircraft/Generic/generic-instrumentation.xml"
		/build/workspace/Linux-nightly/flightgear/src/Autopilot/autopilotgroup.cxx:-203:	Reading property-rule configuration from Path "/fgdata/Aircraft/Generic/generic-autopilot.xml"
		/build/workspace/Linux-nightly/flightgear/src/Autopilot/autopilotgroup.cxx:-215:	adding  property-rule subsystem generic autopilot
		/build/workspace/Linux-nightly/flightgear/src/Autopilot/autopilotgroup.cxx:-203:	Reading property-rule configuration from Path "/fgdata/Aircraft/Generic/generic-autopilot-helper.xml"
		/build/workspace/Linux-nightly/flightgear/src/Autopilot/autopilotgroup.cxx:-215:	adding  property-rule subsystem autopilot helpers

Error 2
	code:error-audio-fx-load
	type:error-type-misconfigured
	when:16:51:21 GMT
	SGXmlSound: node:Wind
	location:/media/attila/back_up/flightgear/DC3-neo
	context:
		primary-aircraft = yes
	preceeding log:
		/build/workspace/Linux-nightly/flightgear/src/Aircraft/flightrecorder.cxx:-254:	FlightRecorder: Recorder configuration #0
		/build/workspace/Linux-nightly/flightgear/src/Aircraft/flightrecorder.cxx:-288:	FlightRecorder: Using custom recorder configuration: Generic Flight Recorder (4 piston engines/4 propellers/4 tanks/3 retractable gear)
		/build/workspace/Linux-nightly/flightgear/src/Aircraft/flightrecorder.cxx:-311:	FlightRecorder: record size is 579 bytes
		/build/workspace/Linux-nightly/flightgear/src/Cockpit/cockpitDisplayManager.cxx:-70:	Reading cockpit displays from Path "/fgdata/Aircraft/Generic/generic-instrumentation.xml"
		/build/workspace/Linux-nightly/flightgear/src/Time/light.cxx:-53:	Initializing Lighting interpolation tables.
		/build/workspace/Linux-nightly/flightgear/src/Sound/fg_fx.cxx:-134:	Reading sound sound from Path "/media/attila/back_up/flightgear/DC3-neo/dc3-neo-sounds.xml"

Error 3
	code:error-missing-shader
	type:error-type-not-found
	when:16:51:23 GMT
	Couldn't find Effect:Aircraft/Douglas-Dc3/Models/Effects/Glass/glass.eff
	location:
	context:
		aircraft-model = Aircraft/DC3-neo/Models/dc-3.xml
		model-xml = /media/attila/back_up/flightgear/DC3-neo/Models/dc-3.xml
		primary-aircraft = yes
	preceeding log:
		/build/workspace/Linux-nightly/flightgear/src/Aircraft/flightrecorder.cxx:-288:	FlightRecorder: Using custom recorder configuration: Generic Flight Recorder (4 piston engines/4 propellers/4 tanks/3 retractable gear)
		/build/workspace/Linux-nightly/flightgear/src/Aircraft/flightrecorder.cxx:-311:	FlightRecorder: record size is 579 bytes
		/build/workspace/Linux-nightly/flightgear/src/Cockpit/cockpitDisplayManager.cxx:-70:	Reading cockpit displays from Path "/fgdata/Aircraft/Generic/generic-instrumentation.xml"
		/build/workspace/Linux-nightly/flightgear/src/Time/light.cxx:-53:	Initializing Lighting interpolation tables.
		/build/workspace/Linux-nightly/flightgear/src/Sound/fg_fx.cxx:-134:	Reading sound sound from Path "/media/attila/back_up/flightgear/DC3-neo/dc3-neo-sounds.xml"
		/build/workspace/Linux-nightly/flightgear/src/Main/ErrorReporter.cxx:-279:	Error:error-type-misconfigured from error-audio-fx-load::SGXmlSound: node:Wind
	/media/attila/back_up/flightgear/DC3-neo

Error 4
	code:error-missing-shader
	type:error-type-not-found
	when:16:51:23 GMT
	couldn't find base effect to inherit from:Aircraft/Douglas-Dc3/Models/Effects/Glass/glass
	location:/media/attila/back_up/flightgear/DC3-neo/Models/Interior/Cockpit/Panel/Instruments/asi2/asi.xml
	context:
		aircraft-model = Aircraft/DC3-neo/Models/dc-3.xml
		model-xml = /media/attila/back_up/flightgear/DC3-neo/Models/dc-3.xml
		primary-aircraft = yes
	preceeding log:
		/build/workspace/Linux-nightly/flightgear/src/Aircraft/flightrecorder.cxx:-311:	FlightRecorder: record size is 579 bytes
		/build/workspace/Linux-nightly/flightgear/src/Cockpit/cockpitDisplayManager.cxx:-70:	Reading cockpit displays from Path "/fgdata/Aircraft/Generic/generic-instrumentation.xml"
		/build/workspace/Linux-nightly/flightgear/src/Time/light.cxx:-53:	Initializing Lighting interpolation tables.
		/build/workspace/Linux-nightly/flightgear/src/Sound/fg_fx.cxx:-134:	Reading sound sound from Path "/media/attila/back_up/flightgear/DC3-neo/dc3-neo-sounds.xml"
		/build/workspace/Linux-nightly/flightgear/src/Main/ErrorReporter.cxx:-279:	Error:error-type-misconfigured from error-audio-fx-load::SGXmlSound: node:Wind
	/media/attila/back_up/flightgear/DC3-neo
		/build/workspace/Linux-nightly/flightgear/src/Main/ErrorReporter.cxx:-279:	Error:error-type-not-found from error-missing-shader::Couldn't find Effect:Aircraft/Douglas-Dc3/Models/Effects/Glass/glass.eff
	

Error 5
	code:error-xml-model-load
	type:error-type-misconfigured
	when:16:51:24 GMT
	Could not find at least one of the following object for animation:'AI0.Orig'
	location:/media/attila/back_up/flightgear/DC3-neo/Models/Interior/Cockpit/Panel/panel-1980.xml
	context:
		aircraft-model = Aircraft/DC3-neo/Models/dc-3.xml
		model-xml = /media/attila/back_up/flightgear/DC3-neo/Models/dc-3.xml
		primary-aircraft = yes
	preceeding log:
		/build/workspace/Linux-nightly/dist/include/simgear/debug/OsgIoCapture.hxx:-37:	
		/build/workspace/Linux-nightly/dist/include/simgear/debug/OsgIoCapture.hxx:-37:	osgDB ac3d reader: could not read texture "."
		/build/workspace/Linux-nightly/dist/include/simgear/debug/OsgIoCapture.hxx:-37:	
		/build/workspace/Linux-nightly/dist/include/simgear/debug/OsgIoCapture.hxx:-37:	Error reading file /media/attila/back_up/flightgear/DC3-neo/Models/Instruments: file not handled
		/build/workspace/Linux-nightly/dist/include/simgear/debug/OsgIoCapture.hxx:-37:	
		/build/workspace/Linux-nightly/dist/include/simgear/debug/OsgIoCapture.hxx:-37:	osgDB ac3d reader: could not read texture "."

Error 6
	code:error-xml-model-load
	type:error-type-not-found
	when:16:51:24 GMT
	Couldn't find file for submodel '': Aircraft/DC3-neo/Models/Pilot/pilot.xml
	location:Aircraft/DC3-neo/Models/Pilot/pilot.xml
	context:
		aircraft-model = Aircraft/DC3-neo/Models/dc-3.xml
		model-xml = /media/attila/back_up/flightgear/DC3-neo/Models/dc-3.xml
		primary-aircraft = yes
	preceeding log:
		/build/workspace/Linux-nightly/dist/include/simgear/debug/OsgIoCapture.hxx:-37:	Error reading file /media/attila/back_up/flightgear/DC3-neo/Models/Instruments: file not handled
		/build/workspace/Linux-nightly/dist/include/simgear/debug/OsgIoCapture.hxx:-37:	
		/build/workspace/Linux-nightly/dist/include/simgear/debug/OsgIoCapture.hxx:-37:	osgDB ac3d reader: could not read texture "."
		/build/workspace/Linux-nightly/flightgear/src/Main/ErrorReporter.cxx:-279:	Error:error-type-misconfigured from error-xml-model-load::Could not find at least one of the following object for animation:'AI0.Orig'
	/media/attila/back_up/flightgear/DC3-neo/Models/Interior/Cockpit/Panel/panel-1980.xml
		/build/workspace/Linux-nightly/simgear/simgear/scene/model/animation.cxx:-498:	Could not find at least one of the following objects for animation: 'AI0.Orig' in file: /media/attila/back_up/flightgear/DC3-neo/Models/Interior/Cockpit/Panel/panel-1980.xml
		/build/workspace/Linux-nightly/simgear/simgear/scene/model/SGReaderWriterXML.cxx:-726:	Failed to load file: "Aircraft/DC3-neo/Models/Pilot/pilot.xml"

Error 7
	code:error-xml-model-load
	type:error-type-not-found
	when:16:51:24 GMT
	Couldn't find file for submodel '': Aircraft/DC3-neo/Models/Pilot/copilot.xml
	location:Aircraft/DC3-neo/Models/Pilot/copilot.xml
	context:
		aircraft-model = Aircraft/DC3-neo/Models/dc-3.xml
		model-xml = /media/attila/back_up/flightgear/DC3-neo/Models/dc-3.xml
		primary-aircraft = yes
	preceeding log:
		/build/workspace/Linux-nightly/dist/include/simgear/debug/OsgIoCapture.hxx:-37:	osgDB ac3d reader: could not read texture "."
		/build/workspace/Linux-nightly/flightgear/src/Main/ErrorReporter.cxx:-279:	Error:error-type-misconfigured from error-xml-model-load::Could not find at least one of the following object for animation:'AI0.Orig'
	/media/attila/back_up/flightgear/DC3-neo/Models/Interior/Cockpit/Panel/panel-1980.xml
		/build/workspace/Linux-nightly/simgear/simgear/scene/model/animation.cxx:-498:	Could not find at least one of the following objects for animation: 'AI0.Orig' in file: /media/attila/back_up/flightgear/DC3-neo/Models/Interior/Cockpit/Panel/panel-1980.xml
		/build/workspace/Linux-nightly/simgear/simgear/scene/model/SGReaderWriterXML.cxx:-726:	Failed to load file: "Aircraft/DC3-neo/Models/Pilot/pilot.xml"
		/build/workspace/Linux-nightly/flightgear/src/Main/ErrorReporter.cxx:-279:	Error:error-type-not-found from error-xml-model-load::Couldn't find file for submodel '': Aircraft/DC3-neo/Models/Pilot/pilot.xml
	Aircraft/DC3-neo/Models/Pilot/pilot.xml
		/build/workspace/Linux-nightly/simgear/simgear/scene/model/SGReaderWriterXML.cxx:-726:	Failed to load file: "Aircraft/DC3-neo/Models/Pilot/copilot.xml"

Error 8
	code:error-xml-load-command
	type:error-type-bad-data
	when:16:51:25 GMT
	loadxml exception:mismatched tag
 at /media/attila/back_up/flightgear/DC3-neo/gui/dialogs/config.xml,
line 161, column 2
	location:/media/attila/back_up/flightgear/DC3-neo/gui/dialogs/config.xml,
line 161, column 2
	context:
	preceeding log:
		/fgdata/Nasal/canvas/map.nas:-458:	loaded Canvas map
		/fgdata/Nasal/globals.nas:-142:	setting listener #125 in /media/attila/back_up/flightgear/DC3-neo/Nasal/tailwheel.nas:43
		/fgdata/Nasal/globals.nas:-142:	setting listener #126 in /media/attila/back_up/flightgear/DC3-neo/Nasal/autopilot-control.nas:5
		/build/workspace/Linux-nightly/flightgear/src/Scripting/NasalSys.cxx:-565:	KI266 dme indicator #0 initialized
		/fgdata/Nasal/globals.nas:-142:	setting listener #127 in /media/attila/back_up/flightgear/DC3-neo/Nasal/autopilot-century.nas:60
		/fgdata/Nasal/globals.nas:-142:	setting listener #128 in /media/attila/back_up/flightgear/DC3-neo/Nasal/gps155.nas:57
`

I know that is a WIP, i hope this could help.
Regards

**Comment by tdammers** [comment]
Yeah, this is all very much WIP, I'm not even looking at non-fatal errors right now. Eventually, it will all get cleaned up, but for now, don't expect this to be anywhere near production ready.

Most of these errors are just missing assets, and those will either be copied over from the original DC-3 (and likely also improved), or the reference will be deleted once I get to that particular part of the aircraft. Some are actual errors, and I will most likely fix them later.
